version: '3.9'

services:
  tresksites-admin:
    build:
      context: .
      dockerfile: _docker/Dockerfile
    labels:
      - 'traefik.http.routers.tresksites-admin.rule=Host(`${PROJECT_BASE_URL}`)'
      - traefik.port=80
      - traefik.docker.network=web
      - traefik.http.routers.tresksites-admin.entrypoints=websecure
      - traefik.http.routers.tresksites-admin.tls.certresolver=myresolver
    container_name: tresksites-admin
    restart: always
    networks:
      - web
      - internal

networks:
  web:
    external: true
  internal:
    external: false
